<!-- All Javascripts -->
<script src="{{ asset('dist_front/js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('dist_front/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('dist_front/js/jquery-ui.js') }}"></script>
<script src="{{ asset('dist_front/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('dist_front/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('dist_front/js/wow.min.js') }}"></script>
<script src="{{ asset('dist_front/js/select2.full.js') }}"></script>
<script src="{{ asset('dist_front/js/sweetalert2.min.js') }}"></script>
<script src="{{ asset('dist_front/js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('dist_front/js/acmeticker.js') }}"></script>
<script src="{{ asset('dist_front/js/moment.min.js') }}"></script>
<script src="{{ asset('dist_front/js/daterangepicker.min.js') }}"></script>
<script src="{{ asset('dist_front/js/sticky_sidebar.js') }}"></script>
<script src="{{ asset('dist_front/js/jquery.meanmenu.js') }}"></script>
<script src="{{ asset('dist_front/js/iziToast.min.js') }}"></script>